---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretAccessTokenName | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  token: "{{ .Values.GitHubToken | b64enc }}"
