apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ template "hostname" . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
        path: /
{{ if .Values.ingress.addTlsBlock }}
  tls:
  - hosts:
    - {{ template "hostname" . }}
{{ end }}
