apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    kubernetes.io/cluster-service: "true"
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: kube-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}
  apiGroup: rbac.authorization.k8s.io
