apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    kubernetes.io/cluster-service: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
      - "endpoints"
    verbs:
      - "get"
      - "watch"
      - "list"
