ServicesDomain: ""
Frontend:
  Branch: "master"
  Image:
    Repository: quay.io/mojanalytics/control-panel-frontend
    Tag: v1.3.14
    PullPolicy: Always
  Environment:
    API_URL: "http://cpanel-master-cpanel"
    AUTH0_CLIENT_ID: ""
    AUTH0_CLIENT_SECRET: ""
    AUTH0_DOMAIN: ""
    ENV: ""
    SENTRY_DSN: ""
    TOOLS_DOMAIN: ""
  ServicePort: 80
  Protocol: "https"

ingress:
  addTlsBlock: true

redis:
  persistence:
    enabled: false
