servicesDomain: ""

ingressClass: nginx

authProxy:
  name: auth-proxy
  image: quay.io/mojanalytics/auth-proxy
  tag: v5.2.6
  imagePullPolicy: IfNotPresent
  containerPort: 3000
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
  cookie_maxage: 36000 #10 hours
  cookie_secret: "tony-montana"

apps:
  - name: alertmanager
    port: 9093
  - name: prometheus
    port: 9090

serviceMonitors:
  - labelSelector: nginx-ingress
    targetNamespace: default
    targetPort: metrics
 # - labelSelector: kubernetes-dashboard
 #   targetNamespace: kube-system
 #   targetPath: /metrics
 #   targetPort: 8443
 #   scrapeInterval: 20s



prometheusOperator:
  crdApiGroup: monitoring.coreos.com
  chartName: prometheus-operator

prometheusRules:
    - name: analytics.rules
      rules:
      - alert: InstanceHighMemoryUsage
        annotations:
          message: '{{ $value }}% of cluster memory is in use'
          summary: High Memory Load
         # Alert if disk utilisation reaches 90%
        expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 90
        for: 10m
        labels:
          severity: warning

      - alert: PreditciveHostDiskSpace
        annotations:
          message: 'Based on recent sampling, the disk is likely to will fill on volume
             {{ $labels.mountpoint }} within the next 5 hours for instace: {{ $labels.instance_id
             }} tagged as: {{ $labels.instance_name_tag }}'
          summary: Predictive Disk Space Utilisation Alert
        expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[4h], 5 * 3600) < 0
        for: 10h
        labels:
          severity: warning

      - alert: HighNumberOfUserHTTPErrors
        annotations:
          message: 'Ingress: {{ $labels.ingress }} has returned {{ $value }} 503 errors in the last 10 minutes'
          summary: User getting a high number of 503 errors
        expr: increase(nginx_ingress_controller_requests{status=~"503", exported_namespace=~"user-.*"}[10m]) > 5
        for: 1m
        label:
          severity: warning
