apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        env:
        - name: CONCOURSE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: CONCOURSE_BASE_URL
        - name: CONCOURSE_WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: CONCOURSE_WEBHOOK_TOKEN
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: SECRET
        readinessProbe:
          httpGet:
            path: /?healthz
            port: http
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /?healthz
            port: http
          initialDelaySeconds: 1
          periodSeconds: 20
