apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
spec:
  rules:
  - host: {{ template "hostname" . }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
{{ if .Values.ingress.addTlsBlock }}
  tls:
  - hosts:
    - {{ template "hostname" . }}
{{ end }}

