apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
type: Opaque
data:
  CONCOURSE_BASE_URL: {{ .Values.concourse.base_url | b64enc | quote }}
  CONCOURSE_WEBHOOK_TOKEN: {{ .Values.concourse.token | b64enc | quote }}
  SECRET: {{ .Values.secret | b64enc | quote }}
