apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    type: cron
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
        spec:
          serviceAccountName: {{ .Release.Name }}
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.image }}"
            env:
            - name: LOG_LEVEL
              value: '{{ .Values.logLevel }}'
            - name: LABEL_SELECTOR
              value: '{{ .Values.labelSelector }}'
            - name: CPU_ACTIVITY_THRESHOLD
              value: '{{ .Values.cpuActivityThreshold }}'
          restartPolicy: Never
