apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
    component: scheduler
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: scheduler

  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: scheduler
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: "init"
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: {{ .Release.Name }}-config
            mountPath: /root/airflow/airflow.cfg
            subPath: airflow.cfg
          - name: {{ .Release.Name }}-dags
            mountPath: "/root/airflow/dags/"
        env:
            {{ include "env" . | indent 12 }}
        command:
          - "bash"
        args:
          - "-cx"
          - >
              cd /usr/local/lib/python3.6/site-packages/airflow &&
              airflow initdb && airflow upgradedb &&
              (
              airflow create_user
              --role Admin
              --username {{ .Values.airflow.admin.username }}
              --password {{ .Values.airflow.admin.password }}
              --firstname {{ .Values.airflow.admin.username }}
              --lastname {{ .Values.airflow.admin.username }}
              --email {{ .Values.airflow.admin.email }} || true
              )

      containers:
        - name: scheduler
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          command:
            - "airflow"
          args:
            - "scheduler"
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.airflow.image.port }}
          env:
            {{ include "env" . | indent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-config
              mountPath: /root/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: {{ .Release.Name }}-dags
              mountPath: "/root/airflow/dags/"
            - name: {{ .Release.Name }}-logs
              mountPath: "/root/airflow/logs/"
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}
        - name: {{ .Release.Name }}-dags
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dags
        - name: {{ .Release.Name }}-logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs
