apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
type: Opaque
data:
  sql-alchemy-conn: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.host .Values.postgres.port .Values.postgres.db | b64enc | quote }}
  fernet-key: {{ printf .Values.airflow.fernetKey | b64enc | quote }}
  secret-key: {{ printf .Values.airflow.secretKey | b64enc | quote }}
  smtp-user: {{ printf .Values.airflow.config.smtp.smtp_user | b64enc | quote }}
  smtp-password: {{ printf .Values.airflow.config.smtp.smtp_password | b64enc | quote }}
