apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
type: Opaque
data:
  sql-alchemy-conn: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.host .Values.postgres.port .Values.postgres.db | b64enc | quote }}
