apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
type: Opaque
data:
  sql-alchemy-conn: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.host .Values.postgres.port .Values.postgres.db | b64enc | quote }}
  fernet-key: {{ printf .Values.airflow.fernetKey | b64enc | quote }}
  secret-key: {{ printf .Values.airflow.secretKey | b64enc | quote }}
  smtp-user: {{ printf .Values.airflow.config.smtp.smtp_user | b64enc | quote }}
  smtp-password: {{ printf .Values.airflow.config.smtp.smtp_password | b64enc | quote }}

  client_secret.json: |
    {
        "web": {
            "issuer": "{{ .Values.airflow.auth.oauth.baseUrl }}",
            "auth_uri": "{{ .Values.airflow.auth.oauth.authorizeUrl }}",
            "client_id": "{{ .Values.airflow.auth.oauth.consumerKey }}",
            "client_secret": "{{ .Values.airflow.auth.oauth.consumerSecret }}",
            "redirect_uris": [
                "https://{{ .Release.Name }}.{{ .Values.toolsDomain }}/oidc_callback"

            ],
            "token_uri": "{{ .Values.airflow.auth.oauth.accessTokenUrl }}",
            "userinfo_uri": "{{ .Values.airflow.auth.oauth.baseUrl }}userinfo"
          }
    }
