apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
spec:
  sessionAffinity: ClientIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.airflow.image.port }}
