apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
    spec:
      serviceAccountName: kube2iam
      hostNetwork: true
      updateStrategy:
        type: RollingUpdate
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--base-role-arn={{ .Values.base_role }}"
            - "--iptables=true"
            - "--host-interface={{ .Values.host_interface }}"
            - "--host-ip=$(HOST_IP)"
            - "--default-role={{ .Values.default_role }}"
            - "--namespace-restrictions=true"
            - "--namespace-restriction-format=regexp"
            {{- if .Values.sts_region }}
            - "--use-regional-sts-endpoint=true"
            {{- end }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.sts_region }}
            - name: AWS_REGION
              value: {{ .Values.sts_region }}
            {{- end }}
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: highmem
