apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2iam
  namespace: default
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
