---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.webapps.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-traffic
  namespace: {{ .Values.webapps.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.ingressController.namespace }}
{{- if .Values.TEMPORARYnetworkPoliciesWithNamespaceAndPodSelectorsSupported }}
      podSelector:
        matchLabels:
{{ toYaml .Values.ingressController.podsMatchLabels | indent 10 -}}
{{- end }}
    ports:
{{ toYaml .Values.webapps.ports | indent 6 }}
