apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.username }}-rstudio
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    host: "{{ include "host" . | trunc 63 }}"
