apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.teams.airflowSupport.name }}
  namespace: {{ .Values.teams.airflowSupport.namespace }}
  labels:
    chart: {{ template "rbac.chart" . }}
  annotations:
    moj-analytical-services/teams: {{ .Values.teams.airflowSupport.name }}
    description: {{ .Values.teams.airflowSupport.description | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.teams.appSupport.name }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ .Values.teams.airflowSupport.name }}
