{{ range .Values.priority_classes }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ .name }}
globalDefault: {{ .global | default "false" }}
value: {{ .priority_value }}
description: {{ .description | quote | default "" }}

---
{{ end }}
