apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
data:
{{ toYaml .Values.config | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pipelines
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
