apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
data:
  prepull.sh: |
    #! /usr/bin/env sh

    set -eu

    CONFIG_FILE=/images-prepuller/images.txt
    IMAGES=$(cat $CONFIG_FILE)

    printf "Pulling images on node '%s'..." "$NODE_NAME"

    for image in $IMAGES; do
        printf "\n\nPulling '%s'..." "$image"
        docker image pull "$image";
    done

  images.txt: |
    {{ range .Values.docker.images }}
    {{- . }}
    {{ end }}
