apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
data:
  prepull.sh: |
    #! /usr/bin/env sh

    echo "Pulling images..."

    for image in `cat images.txt`; do
        echo "\n\nPulling '$image'..."
        docker image pull $image;
    done

  images.txt: |
    {{ range .Values.docker.images }}
    {{- . }}
    {{ end }}
