{{/*
Shared env for workers
*/}}
{{- define "env" }}
- name: SQL_ALCHEMY_CONN
  value: sqlite:////home/{{ .Values.Username }}/airflow/db/airflow.sqlite
- name: FERNET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}
      key: fernet-key
- name: SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}
      key: secret-key
- name: SMTP_USER
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}
      key: smtp-user
- name: SMTP_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}
      key: smtp-password
{{- end }}
