apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Chart.Name }}
    host: {{ template "host" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ template "host" . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
  tls:
    - hosts:
      - {{ template "host" . }}
