apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
type: Opaque
data:
  auth0_domain: {{ .Values.authProxy.auth0_domain | b64enc | quote }}
  auth0_client_id: {{ .Values.authProxy.auth0_client_id | b64enc | quote }}
  auth0_client_secret: {{ .Values.authProxy.auth0_client_secret | b64enc | quote }}
  auth0_callback_url: {{ printf "https://%s/callback" (include "host" .) | b64enc | quote }}
  cookie_secret: {{ .Values.cookie_secret | b64enc | quote }}
  fernet-key: {{ printf .Values.airflow.fernetKey | b64enc | quote }}
  secret-key: {{ printf .Values.airflow.secretKey | b64enc | quote }}
