apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
    host: {{ template "host" . }}
type: Opaque
data:
  auth0_domain: {{ .Values.authProxy.auth0_domain | b64enc | quote }}
  auth0_client_id: {{ .Values.authProxy.auth0_client_id | b64enc | quote }}
  auth0_client_secret: {{ .Values.authProxy.auth0_client_secret | b64enc | quote }}
  auth0_callback_url: {{ printf "https://%s/callback" (include "host" .) | b64enc | quote }}
  cookie_secret: {{ .Values.cookie_secret | b64enc | quote }}
  fernet-key: {{ printf .Values.airflow.fernetKey | b64enc | quote }}
  secret-key: {{ printf .Values.airflow.secretKey | b64enc | quote }}
  smtp-user: {{ printf .Values.airflow.config.smtp.smtp_user | b64enc | quote }}
  smtp-password: {{ printf .Values.airflow.config.smtp.smtp_password | b64enc | quote }}
  admin-username: {{ printf .Values.airflow.admin.username | b64enc | quote }}
  admin-password: {{ printf .Values.airflow.admin.password | b64enc | quote }}
  admin-email: {{ printf .Values.airflow.admin.email | b64enc | quote }}
