apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Release.Name }}
    component: "webserver"
    host: {{ include "unidle_key" . }}
    unidle-key: {{ include "unidle_key" . }}
spec:
  sessionAffinity: ClientIP
  selector:
    app: {{ .Chart.Name }}
    component: "all"
  ports:
    - port: 80
      targetPort: {{ .Values.authProxy.containerPort }}
