apiVersion: v1
entries:
  config-user:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.690802616Z
    description: Configure the user (e.g. git setup, etc...)
    digest: e484c230be1c06b39fe2b4e205abcb47e3d1344e551ddb8db1e6de19dae369a6
    name: config-user
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/config-user-0.1.0.tgz
    version: 0.1.0
  elasticsearch-curator:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.6910896Z
    description: A Helm chart for Kubernetes
    digest: 54e5490ccff6ce64369e0b74b9f7b7b8700ad88d3e8e22ac75b09253b13399f8
    name: elasticsearch-curator
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/elasticsearch-curator-0.1.0.tgz
    version: 0.1.0
  fluentd:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.691344241Z
    description: A Helm chart for Kubernetes
    digest: 8c57a52ac75981eaa80f386b5e7af378b0b04bb2d1d6591d24c05c16a113e18f
    name: fluentd
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/fluentd-0.1.0.tgz
    version: 0.1.0
  init-platform:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.691812616Z
    description: A Helm chart for Kubernetes
    digest: af7f2b2e3d14474542b54782bdf6d013150900fcc4750bda9d20f890f19dcc92
    name: init-platform
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/init-platform-0.1.0.tgz
    version: 0.1.0
  init-user:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.693677427Z
    description: A Helm chart for Kubernetes
    digest: ed07b6706f272ed5fbe72e33ca44921f7aecf30779b223d2da8aeac7678b128e
    name: init-user
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/init-user-0.1.0.tgz
    version: 0.1.0
  kibana-auth-proxy:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.694229722Z
    description: A Helm chart for Kubernetes
    digest: 20cf78f9638fb0f5bffa58304d55fa4cce02c7518349c50643ce88d62b89dc81
    name: kibana-auth-proxy
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kibana-auth-proxy-0.1.0.tgz
    version: 0.1.0
  kube-dashboard:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.694794846Z
    description: A Helm chart for Kubernetes
    digest: 2d82880a250c8088ab368e43e966c95533d6ac0839a1e9443f3756bb5893bd62
    name: kube-dashboard
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube-dashboard-0.1.0.tgz
    version: 0.1.0
  kube2iam:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.695204061Z
    description: Allows k8s pods to be started with AWS IAM roles attached
    digest: 389f30b188fdacedddad1868aa40eb444a359fbaec912db5c9a29c6445071bcd
    name: kube2iam
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube2iam-0.1.0.tgz
    version: 0.1.0
  nfs-migration:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.695712274Z
    description: A Helm chart for Kubernetes
    digest: 02f63fac4170197cbe64221de23c1f0c578057bcf0804f5cd9afc4ed8860772c
    name: nfs-migration
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-migration-0.1.0.tgz
    version: 0.1.0
  nginx-ingress:
  - created: 2017-07-15T18:03:52.697527457Z
    description: An nginx Ingress controller that uses ConfigMap to store the nginx
      configuration.
    digest: e3fb68576a309ef9d044de966fa8adaa0d9664f791d84bb1c3072360ad43d26b
    engine: gotpl
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    maintainers:
    - email: jack.zampolin@gmail.com
      name: Jack Zampolin
    - email: mgoodness@gmail.com
      name: Michael Goodness
    name: nginx-ingress
    sources:
    - https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nginx-ingress-0.3.0.tgz
    version: 0.3.0
  node-exporter:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.698130597Z
    description: A Helm chart for Kubernetes
    digest: 753964efaf9f3ac2e7bdb7c2065362ca38d685b8b9ff183a3ca8b0d9c14a9027
    name: node-exporter
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/node-exporter-0.1.0.tgz
    version: 0.1.0
  rstudio:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.698831684Z
    description: A Helm chart for RStudio
    digest: 77744a5ab26deb668e5bf1d88a00c9a5f75b28186e81d9564b725b7abed0059b
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-0.2.2.tgz
    version: 0.2.2
  shiny-app:
  - apiVersion: v1
    created: 2017-07-15T18:03:52.699533199Z
    description: Shiny app Helm chart for Kubernetes
    digest: f0d8293712dd5680b98bf586c8f1a02b56ffbfc859a60cbb93547ea9e97499f4
    name: shiny-app
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/shiny-app-0.1.0.tgz
    version: 0.1.0
generated: 2017-07-15T18:03:52.690395743Z
