apiVersion: v1
entries:
  calicoctl:
  - appVersion: v1
    created: 2017-08-29T13:23:13.764925215Z
    description: calicoctl command line tool for configuring calico network provider
    digest: 13db458de9cad647ba0df9adeb1988e8ae8fcd974e69107eab58b96545f8ca6f
    name: calicoctl
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/calicoctl-0.1.0.tgz
    version: 0.1.0
  config-user:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.765334645Z
    description: Configure the user (e.g. git setup, etc...)
    digest: e484c230be1c06b39fe2b4e205abcb47e3d1344e551ddb8db1e6de19dae369a6
    name: config-user
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/config-user-0.1.0.tgz
    version: 0.1.0
  elasticsearch-curator:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.766258615Z
    deprecated: true
    description: A Helm chart for Kubernetes
    digest: 5b6422aa20eb331e85c654b55d3f52660eb88e65d6c01bdb821067c5b6e22204
    name: elasticsearch-curator
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/elasticsearch-curator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-08-29T13:23:13.765819662Z
    description: A Helm chart for Kubernetes
    digest: 54e5490ccff6ce64369e0b74b9f7b7b8700ad88d3e8e22ac75b09253b13399f8
    name: elasticsearch-curator
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/elasticsearch-curator-0.1.0.tgz
    version: 0.1.0
  fluentd:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.76679087Z
    description: A Helm chart for Kubernetes
    digest: 8e018e33fc86d97aa991098abe1fa97687c07646b43abb04d4d0dd545e528c21
    name: fluentd
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/fluentd-0.1.0.tgz
    version: 0.1.0
  init-platform:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.767161755Z
    description: A Helm chart for Kubernetes
    digest: af7f2b2e3d14474542b54782bdf6d013150900fcc4750bda9d20f890f19dcc92
    name: init-platform
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/init-platform-0.1.0.tgz
    version: 0.1.0
  init-user:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.769099969Z
    description: A Helm chart for Kubernetes
    digest: ed07b6706f272ed5fbe72e33ca44921f7aecf30779b223d2da8aeac7678b128e
    name: init-user
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/init-user-0.1.0.tgz
    version: 0.1.0
  kibana-auth-proxy:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.770082751Z
    description: A Helm chart for Kubernetes
    digest: dcdb6cff1d5208c81cbddf66c4a035b360876025484b984ec9d5a467551e695e
    name: kibana-auth-proxy
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kibana-auth-proxy-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2017-08-29T13:23:13.769586531Z
    description: A Helm chart for Kubernetes
    digest: 20cf78f9638fb0f5bffa58304d55fa4cce02c7518349c50643ce88d62b89dc81
    name: kibana-auth-proxy
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kibana-auth-proxy-0.1.0.tgz
    version: 0.1.0
  kube-dashboard:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.77063032Z
    description: A Helm chart for Kubernetes
    digest: 2d82880a250c8088ab368e43e966c95533d6ac0839a1e9443f3756bb5893bd62
    name: kube-dashboard
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube-dashboard-0.1.0.tgz
    version: 0.1.0
  kube2iam:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.771460858Z
    description: Allows k8s pods to be started with AWS IAM roles attached
    digest: e03e67fbf416b5f68c36267ee73c008f18e3f31d23b9cdf652807cc6bc49bf80
    name: kube2iam
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube2iam-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-08-29T13:23:13.771086635Z
    description: Allows k8s pods to be started with AWS IAM roles attached
    digest: 389f30b188fdacedddad1868aa40eb444a359fbaec912db5c9a29c6445071bcd
    name: kube2iam
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/kube2iam-0.1.0.tgz
    version: 0.1.0
  nfs-migration:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.77247231Z
    deprecated: true
    description: A Helm chart for Kubernetes
    digest: 945a2d60d842080f7b91c9256e84a04738487d4fbb36d31b50e4b5263cfd9cb2
    name: nfs-migration
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-migration-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-08-29T13:23:13.771938183Z
    description: A Helm chart for Kubernetes
    digest: 02f63fac4170197cbe64221de23c1f0c578057bcf0804f5cd9afc4ed8860772c
    name: nfs-migration
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nfs-migration-0.1.0.tgz
    version: 0.1.0
  nginx-ingress:
  - created: 2017-08-29T13:23:13.773959482Z
    description: An nginx Ingress controller that uses ConfigMap to store the nginx
      configuration.
    digest: e3fb68576a309ef9d044de966fa8adaa0d9664f791d84bb1c3072360ad43d26b
    engine: gotpl
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    maintainers:
    - email: jack.zampolin@gmail.com
      name: Jack Zampolin
    - email: mgoodness@gmail.com
      name: Michael Goodness
    name: nginx-ingress
    sources:
    - https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/nginx-ingress-0.3.0.tgz
    version: 0.3.0
  node-exporter:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.774413857Z
    description: A Helm chart for Kubernetes
    digest: 753964efaf9f3ac2e7bdb7c2065362ca38d685b8b9ff183a3ca8b0d9c14a9027
    name: node-exporter
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/node-exporter-0.1.0.tgz
    version: 0.1.0
  rstudio:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.777542984Z
    description: A Helm chart for RStudio
    digest: 064a104466406eee87a8e0854dc4ea50aa2ad0d8c752ac8d1465d6eb7fff6d78
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    created: 2017-08-29T13:23:13.776975156Z
    description: A Helm chart for RStudio
    digest: 64a3ac54289a10bb0a3ee7773d5b9dfbb870f6034f341821f2753a17b6d9f04d
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    created: 2017-08-29T13:23:13.776312744Z
    description: A Helm chart for RStudio
    digest: a88b4e9241a012dd81062856dc27b78fa0fa107c80fdef2baedf7a635ea96233
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    created: 2017-08-29T13:23:13.775637307Z
    description: A Helm chart for RStudio
    digest: a2df2dfe7aa0d04a6d7de175b134cc2e1e3e1b930f8b2acfdbda52fb396a4329
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    created: 2017-08-29T13:23:13.775017131Z
    description: A Helm chart for RStudio
    digest: f55bd974609c8e7caded4af18170ebf7b8221effacec0a5724f593d4822f0f8b
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/rstudio-0.2.2.tgz
    version: 0.2.2
  shiny-app:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.778816876Z
    deprecated: true
    description: Shiny app Helm chart for Kubernetes
    digest: 1ad76530ca1d5c2cbedb21880e3790fd11d6d9a7282c1beae206d2524e24375a
    name: shiny-app
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/shiny-app-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2017-08-29T13:23:13.778161034Z
    description: Shiny app Helm chart for Kubernetes
    digest: f0d8293712dd5680b98bf586c8f1a02b56ffbfc859a60cbb93547ea9e97499f4
    name: shiny-app
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/shiny-app-0.1.0.tgz
    version: 0.1.0
  webapp:
  - apiVersion: v1
    created: 2017-08-29T13:23:13.780136692Z
    description: webapp Helm chart for Kubernetes
    digest: f7df53771cee6e33fdeed01b83a0f3ab8d7ad9aff906e3983ddd8728f4dd80aa
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v1
    created: 2017-08-29T13:23:13.779464833Z
    description: webapp Helm chart for Kubernetes
    digest: b67c59fb7afa3bb49124bbdc89e8554476c3e456ffd878b89a4091bc51041f4a
    name: webapp
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/charts/webapp-1.0.0.tgz
    version: 1.0.0
generated: 2017-08-29T13:23:13.764325788Z
