apiVersion: v1
entries:
  rstudio:
  - apiVersion: v1
    created: 2017-07-13T16:58:24.559919671+01:00
    description: A Helm chart for RStudio
    digest: a431198b04ce669104a6a4c19a493c7013b3a34994cdcb9ce8c652dda3d8fc7c
    name: rstudio
    urls:
    - https://ministryofjustice.github.io/analytics-platform-helm-charts/rstudio-0.2.2.tgz
    version: 0.2.2
generated: 2017-07-13T16:58:24.559482575+01:00
