# Docker image
image:
  name: quay.io/mojanalytics/go-unidler
  tag: v1.0.4
  pullPolicy: IfNotPresent

unidleKeyLabel: "host"

replicaCount: 3

ingress:
  addTlsBlock: true
  className: "nginx"

service:
  externalPort: 80
  internalPort: 8080
  type: ClusterIP

servicesDomain: ""
