toolsDomain: "tools.EXAMPLE.COM"
Username: ""
airflow:
  secretKey: ""
  fernetKey: ""
  image:
    repository: "quay.io/mojanalytics/airflow"
    tag: "1.10.3"
    pullPolicy: "IfNotPresent"
    port: "8080"
  config:
    core:
      parallelism: "1"
    smtp:
      smtp_host: localhost
      smtp_starttls: true
      smtp_ssl: false
      smtp_user: airflow
      smtp_password: airflow
      smtp_port: 25
      smtp_mail_from: airflow@example.com
    webserver:
      enable_proxy_fix: "True"
service:
  port: 80
authProxy:
  image: "quay.io/mojanalytics/auth-proxy"
  tag: "v2.1.0"
  imagePullPolicy: "IfNotPresent"
  containerPort: "3000"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
  auth0_domain: ""
  auth0_client_id: ""
  auth0_client_secret: "" # put dummy value here to stop helm lint complaining
  cookie_maxage: 36000
aws:
  iamRole: ""
  defaultRegion: "eu-west-1"
cookie_secret: ""
kube2iam:
  allowedRoles: ".*"
  serviceAccountName: ""
