apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: cert-manager
spec:
  # Name of a secret to store tls certificate
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: {{ .Release.Name }}
    kind: ClusterIssuer
  commonName: '{{ .Values.cert.commonname }}'
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  dnsNames:
{{ toYaml .Values.cert.dnsnames | indent 4 }}
