apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
  labels:
    app: cert-manager
    chart: {{ template "cert-manager-resources.chart" . }}
spec:
  acme:
    server: {{ .Values.issuer.acme.server }}
    email: {{ .Values.issuer.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.issuer.acme.solvers.dnsZone | quote }}
        dns01:
          route53:
            region: {{ .Values.issuer.acme.dns01.route53 }}
            role: {{ .Values.issuer.acme.dns01.route53.role }}
