apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-app"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        {{ .Release.Name }}-redis-client: true
      annotations:
        iam.amazonaws.com/role: "{{ .Values.aws.iamRole }}"
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      volumes:
      - emptyDir: {}
        name: nginxconf
      - emptyDir: {}
        name: staticfiles
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: {{ .Values.django.port }}
          envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-env-configmap"
          - secretRef:
              name: "{{ .Release.Name }}-env-secrets"
          - secretRef:
              name: "{{ .Release.Name }}-db-env"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
