apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ include "host" . | trunc 63 }}
rules:
  - apiGroups: [""]
    verbs: ["list"]
    resources: ["pods"]

  - apiGroups: [""]
    verbs: ["create"]
    resources: ["pods/portforward"]

  - apiGroups: ["extensions"]
    verbs: ["get", "list"]
    resources: ["ingresses"]
