apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}-helm-client"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
rules:
  - apiGroups: [""]
    verbs: ["list"]
    resources: ["pods"]

  - apiGroups: [""]
    verbs: ["create"]
    resources: ["pods/portforward"]

  - apiGroups: ["extensions"]
    verbs: ["get", "list"]
    resources: ["ingresses"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Chart.Name }}-read-apps-ingresses"
  namespace: {{ .Values.appsNamespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
rules:
  - apiGroups: ["extensions"]
    verbs: ["get", "list"]
    resources: ["ingresses"]
