apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Chart.Name }}-read-ingresses"
  namespace: {{ .Values.appsNamespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
rules:
  - apiGroups: ["extensions"]
    verbs: ["get", "list"]
    resources: ["ingresses"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Chart.Name }}-read-apps-ingresses"
  namespace: {{ .Values.appsNamespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Chart.Name }}-read-ingresses"
subjects:
  - apiGroup: ""
    name: "{{ .Chart.Name }}"
    kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"
