apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
    host: {{ template "host" . }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
