apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}-worker"
    host: {{ template "host" . }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-worker"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-worker"
        {{ .Release.Name }}-redis-client: true
      annotations:
        iam.amazonaws.com/role: "{{ .Values.aws.iamRole }}"
    spec:
      serviceAccountName: "{{ .Release.Name }}"
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["python3", "manage.py", "runworker", "background_tasks"]
          envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-env-configmap"
          - secretRef:
              name: "{{ .Release.Name }}-env-secrets"
          - secretRef:
              name: "{{ .Release.Name }}-db-env"
