Username: ""
EnvName: "test"
CookieSecret: ""
WebApp:
  Name: ""
  BaseHost: ""
  ReplicaCount: 3
  GithubRepo: ""
  Port: 80
  Image:
    Repository: ""
    Tag: ":latest"
    PullPolicy: Always
AuthProxy:
  AuthenticationRequired: "true"
  IPRanges: ""
  Auth0:
    ClientSecret: ""
    ClientId: ""
    Domain: "AUTH0_USER.eu.auth0.com"
  Image:
    Repository: quay.io/mojanalytics/auth-proxy
    Tag: "v3.1.0"
    PullPolicy: "IfNotPresent"
AWS:
  IAMRole: ""
Fluentd:
  # https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/
  Image:
    Repository: gcr.io/fluentd-elasticsearch/fluentd
    Tag: v2.5.0
    PullPolicy: "IfNotPresent"
Elasticsearch:
  Scheme: "http"
  Host: ""
  Port: "9200"
  Username: ""
  Password: ""
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
