apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
type: Opaque
data:
  auth0_domain: {{ .Values.authProxy.auth0_domain | b64enc | quote }}
  auth0_client_id: {{ .Values.authProxy.auth0_client_id | b64enc | quote }}
  auth0_client_secret: {{ .Values.authProxy.auth0_client_secret | b64enc | quote }}
  auth0_callback_url: {{ printf "https://%s-%s.%s/callback" .Values.Username .Chart.Name .Values.toolsDomain | lower | b64enc | quote }}
  cookie_secret: {{ .Values.cookie_secret | b64enc | quote }}
