apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Release.Name }}
  kind: Role
subjects:
  - apiGroup: ""
    name: {{ .Release.Name }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
