username: ""
toolsDomain: "tools.EXAMPLE.COM"
aws:
  iamRole: ""
  defaultRegion: "eu-west-1"
authProxy:
  appProtocol: "https"
  auth0:
    clientSecret: ""
    clientId: ""
    domain: "AUTH0_USER.eu.auth0.com"
  cookieMaxAge: "28800" # 8 hours in seconds
  cookieSecret: ""
  express:
    host: "0.0.0.0"
    port: 3000
  image:
    repository: quay.io/mojanalytics/rstudio-auth-proxy
    tag: "v1.4.3"
    pullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
rstudio:
  secureCookieKey: ""
  port: "8787"
  image:
    repository: quay.io/mojanalytics/rstudio
    tag: "3.4.2-5"
    pullPolicy: "Always"
  resources:
    limits:
      cpu: 1.5
      memory: 20Gi
    requests:
      cpu: 200m
      memory: 5Gi
