toolsDomain: "tools.EXAMPLE.COM"
airflow:
  secretKey: ""
  fernetKey: ""
  auth:
    type: "AUTH_DB"
    oauth:
      consumerSecret: ""
      consumerKey: ""
      tokenKey: ""
      baseUrl: ""
      authorizeUrl: ""
      accessTokenUrl: ""
  image:
    repository: "quay.io/mojanalytics/airflow"
    tag: "1.10.2-2"
    pullPolicy: "IfNotPresent"
    port: "8080"
  volumes:
    dags:
      nfsServer: ""
      path: "/dags"
    logs:
      nfsServer: ""
      path: "/logs"
  config:
    core:
      parallelism: 32
    smtp:
      smtp_host: localhost
      smtp_starttls: true
      smtp_ssl: false
      smtp_user: airflow
      smtp_password: airflow
      smtp_port: 25
      smtp_mail_from: airflow@example.com
  admin:
    username: ""
    password: ""
    email: ""
gitSync:
  interval: "180"
  repository: "https://github.com/ministryofjustice/analytics-platform-airflow-example-dags"
  branch: "master"
  image:
    repository: "openweb/git-sync"
    tag: "0.0.1"
    pullPolicy: "IfNotPresent"
postgres:
  host: ""
  port: "5432"
  user: "airflow"
  password: ""
  db: "airflow"
redis:
  password: "airflow"
  cluster:
    enabled: false
  persistence:
    enabled: false
kube2iam:
  allowedRoles: ".*"
  serviceAccountName: ""
