toolsDomain: "tools.EXAMPLE.COM"
airflow:
  image:
    repository: "quay.io/mojanalytics/airflow"
    tag: "0.0.3"
    pullPolicy: "IfNotPresent"
    port: "8080"
  volumes:
    dags:
      nfsServer: ""
      path: "/dags"
    logs:
      nfsServer: ""
      path: "/logs"
  config:
    core:
      parallelism: 32
  admin:
    username: ""
    password: ""
    email: ""
postgres:
  host: ""
  port: "5432"
  user: "airflow"
  password: ""
  db: "airflow"
