toolsDomain: "tools.EXAMPLE.COM"
airflow:
  auth:
    type: "AUTH_DB"
    oauth:
      consumer_secret: ""
      consumer_key: ""
      token_key: ""
      base_url: ""
      authorize_url: ""
      access_token_url: ""
  image:
    repository: "quay.io/mojanalytics/airflow"
    tag: "0.0.5"
    pullPolicy: "IfNotPresent"
    port: "8080"
  volumes:
    dags:
      nfsServer: ""
      path: "/dags"
    logs:
      nfsServer: ""
      path: "/logs"
  config:
    core:
      parallelism: 32
  admin:
    username: ""
    password: ""
    email: ""
gitSync:
  interval: "180"
  repository: "https://github.com/ministryofjustice/analytics-platform-airflow-example-dags"
  branch: "master"
  image:
    repository: "openweb/git-sync"
    tag: "0.0.1"
postgres:
  host: ""
  port: "5432"
  user: "airflow"
  password: ""
  db: "airflow"
