toolsDomain: "tools.EXAMPLE.COM"
airflow:
  image:
    repository: "quay.io/mojanalytics/airflow"
    tag: "0.0.2"
    pullPolicy: "IfNotPresent"
    port: "8080"
  config:
    core:
      parallelism: 32
postgres:
  host: ""
  port: "5432"
  user: "airflow"
  password: ""
  db: "airflow"
