apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Chart.Name }}"
data:
  exclude_patterns: |
    \/\.rstudio\/
    \/R\/library\/
    \/packrat\/
    \/\.git\/
    \/\.cache\/
    \/\.Rproj\.user\/
    \/\.RData$
    \/\.Rhistory$
    \/id_rsa$
    \/\.bash_history$
    \/core$
    \/\.conda\/
    \/miniconda3-r\/
    \/\.local\/
    \/Git_Repos\/
    \/SAT+Shapes\/
    \/py-safety\/
    \/\.virtualenvs\/
    \/comparisons\/
    \/Python\/
    \/node_modules\/
  s3_backup_bucket_name: "{{ .Values.AWS.S3.BucketName }}"
