apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  exclude_patterns: |
    \/\.rstudio\/
    \/R\/library\/
    \/packrat\/
    \/.git\/
    \/.cache\/
    \/.Rproj.user\/
    \/id_rsa$
    \/.bash_history$
  s3_backup_bucket_name: "{{ .Values.AWS.S3.BucketName }}"
