apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
spec:
  template:
    metadata:
      name: nfs-backup
      annotations:
        iam.amazonaws.com/role: {{ .Values.AWS.IAMRole }}
    spec:
      containers:
      - image: samepagelabs/s3cmd:1.6.1
        imagePullPolicy: IfNotPresent
        name: s3cmd
        args:
          - sync
          - --rexclude-from=/tmp/s3cmd/exclude_patterns
          - --delete-removed
          - -v
          - /homes/
          - s3://$(S3_BACKUP_BUCKET_NAME)/
        env:
        - name: S3_BACKUP_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: s3_backup_bucket_name
          value:
        volumeMounts:
          - name: nfs-homes
            mountPath: "/homes"
          - name: exclude-patterns
            mountPath: /tmp/s3cmd
      restartPolicy: OnFailure
      volumes:
      - name: nfs-homes
        persistentVolumeClaim:
          claimName: nfs-homes
      - name: exclude-patterns
        configMap:
          name: {{ template "fullname" . }}
