apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}
  annotations:
    iam.amazonaws.com/role: {{ .Values.AWS.IAMRole }}
spec:
  containers:
  - image: garland/docker-s3cmd:latest
    command:
      - sh
      - -c
      - 'while true; do sleep 100; done'
    imagePullPolicy: IfNotPresent
    name: alpine
    volumeMounts:
      - name: nfs-homes
        mountPath: "/homes"
  volumes:
  - name: nfs-homes
    persistentVolumeClaim:
      claimName: nfs-homes
