apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    repo: "{{ .Values.WebApp.GithubRepo }}"
    app: {{ template "fullname" . }}
    host: {{ include "hostname" . | trunc 63 }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  replicas: {{ .Values.WebApp.ReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        host: {{ include "hostname" . | trunc 63 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        iam.amazonaws.com/role: {{ .Values.AWS.IAMRole }}
    spec:
      priorityClassName: "{{ .Chart.Name }}-default"
      serviceAccountName: {{ template "fullname" . }}
      containers:
        - name: auth-proxy
          image: "{{ .Values.AuthProxy.Image.Repository }}:{{ .Values.AuthProxy.Image.Tag }}"
          imagePullPolicy: {{ .Values.AuthProxy.Image.PullPolicy }}
          ports:
            - name: proxy
              containerPort: 3000
          env:
            - name: USER
              value: {{ .Values.Username }}
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: client_id
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: domain
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: callback_url
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: cookie_secret
            - name: TARGET_URL
              value: "http://localhost:{{ .Values.WebApp.Port }}/"
            - name: AUTHENTICATION_REQUIRED
              value: "{{ .Values.AuthProxy.AuthenticationRequired }}"
            - name: IP_RANGES
              value: "{{ .Values.AuthProxy.IPRanges }}"
            - name: AUTH0_PASSWORDLESS
              value: "true"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /healthz
              port: proxy
            initialDelaySeconds: 5
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: proxy
            initialDelaySeconds: 10
            periodSeconds: 2

        - name: webapp
          image: "{{ .Values.WebApp.Image.Repository }}:{{ .Values.WebApp.Image.Tag | replace ":" "" }}"
          imagePullPolicy: {{ .Values.WebApp.Image.PullPolicy }}
          envFrom:
            - secretRef:
                name: "{{ template "fullname" . }}-env-secrets"
          ports:
            - name: webapp
              containerPort: {{ .Values.WebApp.Port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.WebApp.HealthCheck }}
              port: webapp
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: {{ .Values.WebApp.HealthCheck }}
              port: webapp
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 60
          resources:
            requests:
              cpu: 10m
          volumeMounts:
            - name: varlognginx
              mountPath: /var/log/nginx
            - name: varlogshinyserver
              mountPath: /var/log/shiny-server

        - name: fluent-bit
          image: "{{ .Values.FluentBit.Image.Repository }}:{{ .Values.FluentBit.Image.Tag }}"
          imagePullPolicy: {{ .Values.FluentBit.Image.PullPolicy }}
          env:
            - name:  FLUENT_ELASTICSEARCH_SCHEME
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch_scheme
            - name:  FLUENT_ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch_host
            - name:  FLUENT_ELASTICSEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch_port
            - name:  FLUENT_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch_username
            - name:  FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: elasticsearch_password
            - name:  FLUENT_SOURCE_TAG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}-fluent-bit
                  key: source_tag
            - name:  FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}-fluent-bit
                  key: logstash_prefix
          volumeMounts:
            - name: varlognginx
              mountPath: /var/log/nginx
            - name: varlogshinyserver
              mountPath: /var/log/shiny-server
            - name: libsystemddir
              mountPath: /host/lib
              readOnly: true
            - name: fluent-bit-files
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: fluent-bit-files
              mountPath: /fluent-bit/etc/custom_parsers.conf
              subPath: custom_parsers.conf
            - name: fluent-bit-files
              mountPath: /fluent-bit/etc/add_time_nano.lua
              subPath: add_time_nano.lua
          resources:
{{ toYaml .Values.FluentBit.Resources | indent 12 }}
      volumes:
        - name: varlognginx
          emptyDir: {}
        - name: varlogshinyserver
          emptyDir: {}
        - name: fluent-bit-files
          configMap:
            name: {{ template "fullname" . }}-fluent-bit
            items:
            - key: fluent-bit.conf
              path: fluent-bit.conf
            - key: custom_parsers.conf
              path: custom_parsers.conf
            - key: add_time_nano.lua
              path: add_time_nano.lua
        - name: libsystemddir
          hostPath:
            path: /usr/lib64
