apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    repo: "{{ .Values.WebApp.GithubRepo }}"
    app: {{ template "fullname" . }}
