apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    repo: "{{ .Values.WebApp.GithubRepo }}"
    app: {{ template "fullname" . }}
spec:
  sessionAffinity: ClientIP
  ports:
  - port: {{ .Values.WebApp.Port }}
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
