Username: ""
toolsDomain: "tools.example.com"

aws:
  iamRole: ""
  defaultRegion: "eu-west-1"

service:
  port: 80

authProxy:
  image: quay.io/mojanalytics/auth-proxy
  tag: v5.2.4
  imagePullPolicy: IfNotPresent
  containerPort: 3000
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  auth0_domain: ""
  auth0_client_id: ""
  auth0_client_secret: "" # put dummy value here to stop helm lint complaining
  cookie_maxage: 36000 #10 hours
  tunnel:
    enabled: "true"
    port_range: "8050,4040-4050"

jupyter:
  image: quay.io/mojanalytics/datascience-notebook
  # image: quay.io/mojanalytics/all-spark
  tag: v0.6.9
  # tag: add-nbstripout
  imagePullPolicy: IfNotPresent
  containerPort: 8888
  resources:
    limits:
      cpu: 1.5
      memory: 12Gi
    requests:
      cpu: 1.5
      memory: 12Gi

cookie_secret: ""
