apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.authProxy.name }}
    chart: {{ $.Chart.Name }}
type: Opaque
data:
  auth0Domain: {{ printf "%s" $.Values.grafana.env.GF_AUTH_GENERIC_OAUTH_AUTH_URL | replace "https://" "" | replace "/authorize" ""  | b64enc | quote }}
  auth0ClientId: {{ $.Values.grafana.env.GF_AUTH_GENERIC_OAUTH_CLIENT_ID | b64enc | quote }}
  auth0ClientSecret: {{ $.Values.grafana.env.GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET | b64enc | quote }}
  cookieSecret: {{ $.Values.authProxy.cookie_secret | b64enc | quote }}
