{{ range .Values.apps }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.authProxy.name }}
    target: {{ .name }}
    chart: {{ $.Chart.Name }}
---
{{ end }}
